### ISSUE TITLE
Error 409 Conflict: npm login --registry=https://npm.proplugins.org --scope=@proplugins

### ISSUE THREAD

**Issue by jpmartinsson** [NathanaelA/nativescript.rocks#7]
I am trying to do `tns plugin add @proplugins/nativescript-localstorage@latest`, but get the following error:
```
code E401
Unable to authenticate, your authentication token seems to be invalid.
To correct this please trying logging in again with:
npm login
```
I suppose this is due to not being logged into npm, so I do `npm login --registry=https://npm.proplugins.org --scope=@proplugins`, but get the following error:
```
code E409
409 Conflict - PUT https://npm.proplugins.org/-/user/org.couchdb.user:jmarti02 - user registration disabled
```
The full error log shows this:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'login',
1 verbose cli   '--registry=https://npm.proplugins.org',
1 verbose cli   '--scope=@proplugins' ]
2 info using npm@6.13.0
3 info using node@v10.16.0
4 verbose npm-session c0e9bbbe4925d641
5 verbose web login before first POST
6 http fetch POST 404 https://npm.proplugins.org/-/v1/login 593ms
7 verbose web login not supported, trying couch
8 verbose login before first PUT { _id: 'org.couchdb.user:jmarti02',
8 verbose login   name: '<replaced my username>',
8 verbose login   password: 'XXXXX',
8 verbose login   type: 'user',
8 verbose login   roles: [],
8 verbose login   date: '2019-12-10T22:35:12.055Z' }
9 http fetch PUT 409 https://npm.proplugins.org/-/user/org.couchdb.user:<replaced my username> 398ms
10 http fetch GET 200 https://npm.proplugins.org/-/user/org.couchdb.user:<replaced my username>?write=true 149ms
11 http fetch PUT 409 https://npm.proplugins.org/-/user/org.couchdb.user:<replaced my username>/-rev/undefined 140ms
12 verbose adduser before first PUT { _id: 'org.couchdb.user:j<replaced my username>',
12 verbose adduser   name: '<replaced my username>',
12 verbose adduser   password: 'XXXXX',
12 verbose adduser   email: '<Replaced my email adress>',
12 verbose adduser   type: 'user',
12 verbose adduser   roles: [],
12 verbose adduser   date: '2019-12-10T22:35:12.746Z' }
13 http fetch PUT 409 https://npm.proplugins.org/-/user/org.couchdb.user:<replaced my username> 131ms
14 verbose stack Error: 409 Conflict - PUT https://npm.proplugins.org/-/user/org.couchdb.user:<replaced my username> - user registration disabled
14 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
14 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
15 verbose statusCode 409
16 verbose cwd /Users/<Replaced the path to my project>
17 verbose Darwin 19.0.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "login" "--registry=https://npm.proplugins.org" "--scope=@proplugins"
19 verbose node v10.16.0
20 verbose npm  v6.13.0
21 error code E409
22 error 409 Conflict - PUT https://npm.proplugins.org/-/user/org.couchdb.user:<replaced my username> - user registration disabled
23 verbose exit [ 1, true ]
```
What could be the problem?

**Comment by jpmartinsson** [comment]
Wrong password. Sorry!
